### ISSUE TITLE
Please help. I was unable to install this.

### ISSUE THREAD

**Issue by techviki** [RMuskovets/zd1211-firmware#1]
Hello,

I was unable to install this on kali linux as I am a noob.
Can you please help me install this, since there is no config or makefile, I need guidance to do it.

Thanks.

**Comment by RMuskovets** [comment]
So, this is a repo I used to install firmware for my USB 3com dongle on a archiso. It'll probably work on other distros too, so here's a tutorial (I haven't tested it):
1. `git clone` it.
2. Copy all files that start in `zd1211_` from `lib/firmware` to `/usr/lib/firmware/zd1211`.
For further info, look into `lib/firmware/README`.

**Comment by RMuskovets** [comment]
Also, I'm going to put this in README.md.
